### ISSUE TITLE
Error building fauxdacious

### ISSUE THREAD

**Issue by Hostuu** [wildstar84/fauxdacious#18] opened 2024-10-22 00:06 UTC
cd /tmp/fauxdacious
        ./autogen.sh
        ./configure --prefix=/usr/local [--enable-qt] --with-buildstamp=Fauxdacious
        make
        sudo make install

        sudo ldconfig
configure: WARNING: you should use --build, --host, --target
configure: WARNING: invalid host type: [--enable-qt]
checking build system type... Invalid configuration `[--enable-qt]': machine `[--enable' not recognized
configure: error: /bin/bash ./build-aux/config.sub [--enable-qt] failed
Makefile:20: extra.mk: No such file or directory
make: *** No rule to make target 'extra.mk'.  Stop.
Makefile:20: extra.mk: No such file or directory
make: *** No rule to make target 'extra.mk'.  Stop.

Reproduce:
Linux mint 21.3 cinnamon
Use the build fauxdacious commands in the readme
It will return this error

**Comment by wildstar84** [comment] 2024-10-22 13:30
Do you have all the development packages and gcc installed? (sudo apt-get install git automake build-essential...) In other words, everything necessary to compile and link a C++ program? Each of the commands (autogen.sh, configure, etc.) must be run separately because the way you show it here it looks like "make" was run before "configure" had completed or erred. Otherwise, it looks like your system is not set up properly to generate a valid Makefile.


     On Monday, October 21, 2024 at 07:07:07 PM CDT, Hostuu ***@***.***> wrote:  
 
 


cd /tmp/fauxdacious
./autogen.sh
./configure --prefix=/usr/local [--enable-qt] --with-buildstamp=Fauxdacious
make
sudo make install
    sudo ldconfig
configure: WARNING: you should use --build, --host, --target
configure: WARNING: invalid host type: [--enable-qt]
checking build system type... Invalid configuration [--enable-qt]': machine [--enable' not recognized
configure: error: /bin/bash ./build-aux/config.sub [--enable-qt] failed
Makefile:20: extra.mk: No such file or directory
make: *** No rule to make target 'extra.mk'. Stop.
Makefile:20: extra.mk: No such file or directory
make: *** No rule to make target 'extra.mk'. Stop.

Reproduce:
Linux mint 21.3 cinnamon
Use the build fauxdacious commands in the readme
It will return this error

**Comment by lecheel** [comment] 2024-11-13 11:19
I'm in ubuntu 22.04 
./configure --prefix=/usr/local --enable-qt5 --with-buildstamp=Fauxdacious
may solve the problem
but I'm suck with 
```
Leaving directory songchange.
Entering directory scrobbler2.
In file included from scrobbler.cc:21:
scrobbler.h:22:10: fatal error: libaudcore/mainloop.h: No such file or directory
   22 | #include <libaudcore/mainloop.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Failed to compile scrobbler.cc (plugin)!
make[5]: *** [../../buildsys.mk:532: scrobbler.plugin.o] Error 1
```

**Comment by wildstar84** [comment] 2024-11-13 13:56
My bad - "libaudcore" should be "libfauxdcore" in scrobbler.h!  (It worked for me b/c I also have Audacious's source-tree built on my box)  Anyway, I just fixed and committed, but rather than download the commit, just simply change line 22 to "libfauxdcore", then in the scrobbler2 directory run "make", then "sudo make install", then re-enable scrobbler2 and you'll then have scrobbler2 too!

Thanks for reporting & clarifying!

Jim

**Comment by wildstar84** [comment] 2024-11-17 07:10
No, it does not, sorry.  Patches welcome though!

**Closed by wildstar84** 2024-11-17 07:10 UTC
